### ISSUE TITLE
Use user's nickname if present instead of their username

### ISSUE THREAD

**Issue by eamonburns** [btc-raspberrypiclub/piclub-bot#11]

**Comment by joshbuker** [comment]
https://github.com/joshbuker/discord-bot/blob/main/lib/discord_bot/events/message.rb#L24

https://discordpy.readthedocs.io/en/stable/api.html?highlight=message#discord.abc.User
https://discordpy.readthedocs.io/en/stable/api.html?highlight=message#discord.Member

Looks like the implementation would be pretty close to 1:1 between Ruby and Python for this.
